"""
models/learning_path.py - Learning Path and Path Module models.
Stores generated learning paths for each learner.
"""

import json
from datetime import datetime
from .database import db


class LearningPath(db.Model):
    """
    Learning path generated by CBR + RBR for a specific user.
    Contains the ordered list of modules to complete.
    """
    __tablename__ = 'learning_paths'

    id              = db.Column(db.Integer, primary_key=True)
    user_id         = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    title           = db.Column(db.String(300), nullable=False)
    domain          = db.Column(db.String(100), nullable=True)
    description     = db.Column(db.Text,        nullable=True)
    total_modules   = db.Column(db.Integer,     default=0)
    estimated_hours = db.Column(db.Float,       default=0.0)
    difficulty      = db.Column(db.String(30),  nullable=True)

    # CBR metadata
    cbr_cases_used_json  = db.Column(db.Text, nullable=True)   # IDs of similar cases used
    cbr_similarity_json  = db.Column(db.Text, nullable=True)   # Similarity scores
    rbr_rules_applied_json = db.Column(db.Text, nullable=True) # Rules that were applied

    # Status
    status          = db.Column(db.String(30), default='active')  # active, completed, abandoned
    is_current      = db.Column(db.Boolean,    default=True)
    completed_at    = db.Column(db.DateTime,   nullable=True)
    certificate_path = db.Column(db.String(500), nullable=True)
    created_at      = db.Column(db.DateTime,   default=datetime.utcnow)

    # Relationships
    path_modules = db.relationship(
        'LearningPathModule', backref='learning_path',
        lazy=True, order_by='LearningPathModule.order_index',
        cascade='all, delete-orphan'
    )
    progress = db.relationship('Progress', backref='learning_path', lazy=True, cascade='all, delete-orphan')

    def get_completion_percentage(self) -> float:
        """Calculate % of modules completed."""
        if not self.path_modules:
            return 0.0
        completed = sum(1 for pm in self.path_modules if pm.is_completed)
        return round((completed / len(self.path_modules)) * 100, 1)

    def get_cbr_cases(self) -> list:
        return json.loads(self.cbr_cases_used_json) if self.cbr_cases_used_json else []

    def get_rbr_rules(self) -> list:
        return json.loads(self.rbr_rules_applied_json) if self.rbr_rules_applied_json else []

    def to_dict(self) -> dict:
        return {
            'id': self.id,
            'user_id': self.user_id,
            'title': self.title,
            'domain': self.domain,
            'description': self.description,
            'total_modules': self.total_modules,
            'estimated_hours': self.estimated_hours,
            'difficulty': self.difficulty,
            'status': self.status,
            'completion_percentage': self.get_completion_percentage(),
            'cbr_cases': self.get_cbr_cases(),
            'rbr_rules': self.get_rbr_rules(),
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'certificate_path': self.certificate_path,
        }

    def __repr__(self):
        return f'<LearningPath user={self.user_id} title={self.title[:50]}>'


class LearningPathModule(db.Model):
    """
    Junction table: ordered modules within a learning path.
    Tracks completion status per module.
    """
    __tablename__ = 'learning_path_modules'

    id              = db.Column(db.Integer, primary_key=True)
    learning_path_id = db.Column(db.Integer, db.ForeignKey('learning_paths.id'), nullable=False)
    module_id       = db.Column(db.Integer, db.ForeignKey('modules.id'), nullable=False)
    order_index     = db.Column(db.Integer, default=0)
    is_completed    = db.Column(db.Boolean, default=False)
    is_locked       = db.Column(db.Boolean, default=False)   # Locked until previous completed
    completed_at    = db.Column(db.DateTime, nullable=True)
    assessment_score = db.Column(db.Float,   nullable=True)   # Post-module quiz score

    # Relationship to Module
    module = db.relationship('Module', backref='path_entries', lazy=True)

    def mark_completed(self, score: float = None):
        """Mark this module as completed with optional assessment score."""
        self.is_completed = True
        self.completed_at = datetime.utcnow()
        if score is not None:
            self.assessment_score = score

    def to_dict(self) -> dict:
        module_data = self.module.to_dict() if self.module else {}
        module_data.update({
            'path_module_id': self.id,
            'order_index': self.order_index,
            'is_completed': self.is_completed,
            'is_locked': self.is_locked,
            'completed_at': self.completed_at.isoformat() if self.completed_at else None,
            'assessment_score': self.assessment_score,
        })
        return module_data

    def __repr__(self):
        return f'<PathModule path={self.learning_path_id} module={self.module_id} order={self.order_index}>'
